### ISSUE TITLE
Move API over to this organization

### ISSUE THREAD

**Issue by sixcare** [Turplanlegger/turplanlegger-api#144]
https://github.com/sixcare/turplanlegger-api

## To-do

- [x] Move repository to this project
- [x] Add latest and version tag
- [x] Change tag names in [deploy docker CI](https://github.com/sixcare/turplanlegger-api/blob/main/.github/workflows/publish-docker-image.yaml)
- [x] Change urls in [deploy script](https://github.com/sixcare/turplanlegger-api/blob/main/deploy/deploy.sh)
- [x] Change urls in [development deploy script](https://github.com/sixcare/turplanlegger-api/blob/main/deploy/deploy-develop.sh)
- [x] Update [pyproject.toml](https://github.com/sixcare/turplanlegger-api/blob/main/pyproject.toml)
- [x] Update [README.md](https://github.com/sixcare/turplanlegger-api/blob/main/README.md)
- [x] Generate new deploy tokens
- [x] Generate new secretes for CD use

1. Ensure that the deploy of docker image is run when latest tag is updated.
2. Ensure that check deploy is run when new docker image has been pushed
